In [1]:
# Create a SQLite database

from pathlib import Path
Path('spotify_music.db').touch()

In [2]:
# Create a SQLite table

import sqlite3
conn = sqlite3.connect('spotify.db')
c = conn.cursor()

In [3]:
# Execute query to create music_genre table and associated columns

c.execute('''CREATE TABLE music (song_id int, 
                                 artist_names text,
                                 artists_id int,
                                 danceability int,
                                 energy int,
                                 valence int,
                                 tempo int,
                                 loudness int,
                                 mode int,
                                 key int,
                                 acousticness int,
                                 instrumentalness int,
                                 liveness int,
                                 speechiness int,
                                 explicit int,
                                 duration_ms int,
                                 popularity int,
                                 year date,
                                 release_date date,
                                 song_title text,
                                 genre text)''')

In [4]:
# Load music_genre csv into SQLite table

import pandas as pd

# load the data into a Pandas DataFrame
music = pd.read_csv('music_genre.csv')
music.head(10)

,song_id,artist_names,artists_id,danceability,energy,valence,tempo,loudness,mode,key,...,instrumentalness,liveness,speechiness,explicit,duration_ms,popularity,year,release_date,song_title,genre
0,0,"[""Fat Freddy's Drop""]",[178301],0.600,0.365,0.131,130.046,-13.083,0,9,...,0.585000,0.0921,0.0498,0,437200,54,2005,2005,Ernie,Electronic
1,1,"[""Fat Freddy's Drop""]",[178301],0.874,0.326,0.179,119.620,-13.302,0,11,...,0.148000,0.0993,0.1310,0,581008,53,2005,2005,Wandering Eye,Electronic
2,2,"[""Fat Freddy's Drop""]",[178301],0.670,0.531,0.336,139.385,-8.267,0,9,...,0.345000,0.3060,0.0377,0,431293,55,2009,8/7/09,The Raft,Electronic
3,3,"[""Alexander O'Neal""]",[625201],0.761,0.702,0.850,104.773,-8.523,1,7,...,0.000031,0.0935,0.0389,0,304427,34,1991,1/1/91,All True Man,R&B;
4,4,"[""Alexander O'Neal""]",[625201],0.661,0.828,0.902,115.078,-12.673,0,11,...,0.000001,0.2870,0.0390,0,264933,37,1987,7/29/87,(What Can I Say) To Make You Love Me,R&B;
5,5,"[""Alexander O'Neal""]",[625201],0.719,0.650,0.953,105.141,-12.947,0,7,...,0.000044,0.1330,0.0265,0,277773,34,1987,7/29/87,The Lovers,R&B;
6,6,"[""Alexander O'Neal""]",[625201],0.649,0.245,0.273,112.709,-17.585,1,11,...,0.000000,0.1740,0.0286,0,312733,29,1987,7/29/87,Crying Overtime,R&B;
7,7,"[""Alexander O'Neal""]",[625201],0.701,0.715,0.735,101.515,-14.999,0,11,...,0.000000,0.3540,0.0291,0,241107,32,1987,7/29/87,Hearsay,R&B;
8,8,"[""Alexander O'Neal""]",[625201],0.629,0.414,0.458,138.932,-15.002,1,1,...,0.000802,0.0731,0.0299,0,359200,47,1987,7/29/87,Sunshine,R&B;
9,9,"[""Alexander O'Neal""]",[625201],0.624,0.555,0.185,81.102,-9.646,0,5,...,0.000391,0.2240,0.0271,0,370560,48,1995,10/1/95,If You Were Here *******,R&B;